name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: 2.18
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          sudo apt-get install texlive-latex-base -y 
          sudo apt-get install texlive-fonts-recommended -y 
          #echo "Lorem ipsum" > lorem_1.md  # create two example files
          #echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"
          cd pandoc
          pandoc -o test.pdf test.md 
            
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
